version: '3.8'

services:
  client:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: client
    ports:
      - "5173:5173"
    environment:
      - VITE_BACKEND_URL=http://localhost:8000
    volumes:
      - ./client:/app/client
      - /app/client/node_modules
    depends_on:
      - server

  server:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: server
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app/server
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://myuser:mypassword@db/faultfinderdb
      - DEBUG=TRUE
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: faultfinderdb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
