name: Deploy to Digital Ocean

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository 
      uses: actions/checkout@v3
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Build and Tag Docker Images
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/client:latest --target=client -f Dockerfile .
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/server:latest --target=server -f Dockerfile .

    - name: Push Images to Docker Hub
      run: |
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/client:latest
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/server:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push  

    steps:
    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa_do
        chmod 600 ~/.ssh/id_rsa_do
        ssh-keyscan -H ${{ secrets.DROPLET_IP }} >> ~/.ssh/known_hosts

    - name: Deploy to DigitalOcean
      run: |
        ssh root@${{ secrets.DROPLET_IP }} << 'EOF'
          cd /root/fault-finder-project

          docker-compose down

                    
          
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/client:latest
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/server:latest
          
          docker compose -f docker-compose.yml up -d

          docker compose exec server python manage.py migrate
          
          docker system prune -f

        EOF